name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Set TERM environment variable
      run: echo "TERM=xterm-256color" >> $GITHUB_ENV

    - name: Set FORCE_COLOR
      run: echo "FORCE_COLOR=1" >> $GITHUB_ENV

    - name: Set COLUMNS environment variable
      run: echo "COLUMNS=$(tput cols)" >> $GITHUB_ENV

    - name: Check COLUMNS value
      run: echo "COLUMNS=$COLUMNS"

    - name: Run tests
      run: |
        npm test > test-results.txt

    - name: Convert ANSI to HTML
      run: |
        npx ansi-to-html < test-results.txt > test-results.html

    - name: Save as Markdown
      run: |
        echo '## Latest Test Results' > TESTS.md
        echo '<div>' >> TESTS.md
        cat test-results.html >> TESTS.md
        echo '</div>' >> TESTS.md

    - name: Commit and push TESTS.md
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add TESTS.md
        git commit -m 'Add latest test results'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

